### ISSUE TITLE
add reserved words to the generator

### ISSUE THREAD

**Issue by brabalan** [jscert/jsexplain#13]
The generator should not accept variable names that are reserved JavaScript words.

**Comment by IgnoredAmbience** [comment]
Turns out that we already did special-case `arguments`, `eval`, and `caller` keywords, we just hadn't bothered completing the rest of the list.
Currently these are unsupported as identifiers in the ocaml source code. I propose to permit them, but to prefix the variable name with a `$` character. We already use `$` in place of `'`, and ocaml does not permit `'` as the first character of an identifier, so we should be safe to use it as a prefix.

**Comment by IgnoredAmbience** [comment]
Fixed in 68fef4b.

**Comment by IgnoredAmbience** [comment]
If anyone has any preference for a symbol to prefix these identifiers other than 𝕍, feel free to suggest one/update the code.
